# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ann.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
    name='ann.proto',
    package='ann',
    syntax='proto3',
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\tann.proto\x12\x03\x61nn\x1a\x1bgoogle/protobuf/empty.proto\"%\n\x08Neighbor\x12\n\n\x02id\x18\x01 \x01(\x04\x12\r\n\x05score\x18\x02 \x01(\x02\"\x15\n\x06Vector\x12\x0b\n\x03val\x18\x01 \x03(\x02\"D\n\rSearchRequest\x12\x1a\n\x05query\x18\x01 \x01(\x0b\x32\x0b.ann.Vector\x12\t\n\x01k\x18\x02 \x01(\x04\x12\x0c\n\x04name\x18\x03 \x01(\t\"2\n\x0eSearchResponse\x12 \n\tneighbors\x18\x01 \x03(\x0b\x32\r.ann.Neighbor\"8\n\x11SearchByIdRequest\x12\n\n\x02id\x18\x01 \x01(\x04\x12\t\n\x01k\x18\x02 \x01(\x04\x12\x0c\n\x04name\x18\x03 \x01(\t\"J\n\x12SearchByIdResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\x04\x12 \n\tneighbors\x18\x02 \x03(\x0b\x32\r.ann.Neighbor\"$\n\x11HeartbeatResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xbd\x01\n\nAnnService\x12;\n\theartbeat\x12\x16.google.protobuf.Empty\x1a\x16.ann.HeartbeatResponse\x12\x31\n\x06search\x12\x12.ann.SearchRequest\x1a\x13.ann.SearchResponse\x12?\n\x0csearch_by_id\x12\x16.ann.SearchByIdRequest\x1a\x17.ann.SearchByIdResponseb\x06proto3',
    dependencies=[
        google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,
    ],
)


_NEIGHBOR = _descriptor.Descriptor(
    name='Neighbor',
    full_name='ann.Neighbor',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='id',
            full_name='ann.Neighbor.id',
            index=0,
            number=1,
            type=4,
            cpp_type=4,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name='score',
            full_name='ann.Neighbor.score',
            index=1,
            number=2,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=47,
    serialized_end=84,
)


_VECTOR = _descriptor.Descriptor(
    name='Vector',
    full_name='ann.Vector',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='val',
            full_name='ann.Vector.val',
            index=0,
            number=1,
            type=2,
            cpp_type=6,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=86,
    serialized_end=107,
)


_SEARCHREQUEST = _descriptor.Descriptor(
    name='SearchRequest',
    full_name='ann.SearchRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='query',
            full_name='ann.SearchRequest.query',
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name='k',
            full_name='ann.SearchRequest.k',
            index=1,
            number=2,
            type=4,
            cpp_type=4,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name='name',
            full_name='ann.SearchRequest.name',
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=109,
    serialized_end=177,
)


_SEARCHRESPONSE = _descriptor.Descriptor(
    name='SearchResponse',
    full_name='ann.SearchResponse',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='neighbors',
            full_name='ann.SearchResponse.neighbors',
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=179,
    serialized_end=229,
)


_SEARCHBYIDREQUEST = _descriptor.Descriptor(
    name='SearchByIdRequest',
    full_name='ann.SearchByIdRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='id',
            full_name='ann.SearchByIdRequest.id',
            index=0,
            number=1,
            type=4,
            cpp_type=4,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name='k',
            full_name='ann.SearchByIdRequest.k',
            index=1,
            number=2,
            type=4,
            cpp_type=4,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name='name',
            full_name='ann.SearchByIdRequest.name',
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=231,
    serialized_end=287,
)


_SEARCHBYIDRESPONSE = _descriptor.Descriptor(
    name='SearchByIdResponse',
    full_name='ann.SearchByIdResponse',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='request_id',
            full_name='ann.SearchByIdResponse.request_id',
            index=0,
            number=1,
            type=4,
            cpp_type=4,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name='neighbors',
            full_name='ann.SearchByIdResponse.neighbors',
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=289,
    serialized_end=363,
)


_HEARTBEATRESPONSE = _descriptor.Descriptor(
    name='HeartbeatResponse',
    full_name='ann.HeartbeatResponse',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='message',
            full_name='ann.HeartbeatResponse.message',
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=365,
    serialized_end=401,
)

_SEARCHREQUEST.fields_by_name['query'].message_type = _VECTOR
_SEARCHRESPONSE.fields_by_name['neighbors'].message_type = _NEIGHBOR
_SEARCHBYIDRESPONSE.fields_by_name['neighbors'].message_type = _NEIGHBOR
DESCRIPTOR.message_types_by_name['Neighbor'] = _NEIGHBOR
DESCRIPTOR.message_types_by_name['Vector'] = _VECTOR
DESCRIPTOR.message_types_by_name['SearchRequest'] = _SEARCHREQUEST
DESCRIPTOR.message_types_by_name['SearchResponse'] = _SEARCHRESPONSE
DESCRIPTOR.message_types_by_name['SearchByIdRequest'] = _SEARCHBYIDREQUEST
DESCRIPTOR.message_types_by_name['SearchByIdResponse'] = _SEARCHBYIDRESPONSE
DESCRIPTOR.message_types_by_name['HeartbeatResponse'] = _HEARTBEATRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Neighbor = _reflection.GeneratedProtocolMessageType(
    'Neighbor',
    (_message.Message,),
    {
        'DESCRIPTOR': _NEIGHBOR,
        '__module__': 'ann_pb2'
        # @@protoc_insertion_point(class_scope:ann.Neighbor)
    },
)
_sym_db.RegisterMessage(Neighbor)

Vector = _reflection.GeneratedProtocolMessageType(
    'Vector',
    (_message.Message,),
    {
        'DESCRIPTOR': _VECTOR,
        '__module__': 'ann_pb2'
        # @@protoc_insertion_point(class_scope:ann.Vector)
    },
)
_sym_db.RegisterMessage(Vector)

SearchRequest = _reflection.GeneratedProtocolMessageType(
    'SearchRequest',
    (_message.Message,),
    {
        'DESCRIPTOR': _SEARCHREQUEST,
        '__module__': 'ann_pb2'
        # @@protoc_insertion_point(class_scope:ann.SearchRequest)
    },
)
_sym_db.RegisterMessage(SearchRequest)

SearchResponse = _reflection.GeneratedProtocolMessageType(
    'SearchResponse',
    (_message.Message,),
    {
        'DESCRIPTOR': _SEARCHRESPONSE,
        '__module__': 'ann_pb2'
        # @@protoc_insertion_point(class_scope:ann.SearchResponse)
    },
)
_sym_db.RegisterMessage(SearchResponse)

SearchByIdRequest = _reflection.GeneratedProtocolMessageType(
    'SearchByIdRequest',
    (_message.Message,),
    {
        'DESCRIPTOR': _SEARCHBYIDREQUEST,
        '__module__': 'ann_pb2'
        # @@protoc_insertion_point(class_scope:ann.SearchByIdRequest)
    },
)
_sym_db.RegisterMessage(SearchByIdRequest)

SearchByIdResponse = _reflection.GeneratedProtocolMessageType(
    'SearchByIdResponse',
    (_message.Message,),
    {
        'DESCRIPTOR': _SEARCHBYIDRESPONSE,
        '__module__': 'ann_pb2'
        # @@protoc_insertion_point(class_scope:ann.SearchByIdResponse)
    },
)
_sym_db.RegisterMessage(SearchByIdResponse)

HeartbeatResponse = _reflection.GeneratedProtocolMessageType(
    'HeartbeatResponse',
    (_message.Message,),
    {
        'DESCRIPTOR': _HEARTBEATRESPONSE,
        '__module__': 'ann_pb2'
        # @@protoc_insertion_point(class_scope:ann.HeartbeatResponse)
    },
)
_sym_db.RegisterMessage(HeartbeatResponse)


_ANNSERVICE = _descriptor.ServiceDescriptor(
    name='AnnService',
    full_name='ann.AnnService',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=404,
    serialized_end=593,
    methods=[
        _descriptor.MethodDescriptor(
            name='heartbeat',
            full_name='ann.AnnService.heartbeat',
            index=0,
            containing_service=None,
            input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
            output_type=_HEARTBEATRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name='search',
            full_name='ann.AnnService.search',
            index=1,
            containing_service=None,
            input_type=_SEARCHREQUEST,
            output_type=_SEARCHRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name='search_by_id',
            full_name='ann.AnnService.search_by_id',
            index=2,
            containing_service=None,
            input_type=_SEARCHBYIDREQUEST,
            output_type=_SEARCHBYIDRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_ANNSERVICE)

DESCRIPTOR.services_by_name['AnnService'] = _ANNSERVICE

# @@protoc_insertion_point(module_scope)
