name: Build

on: [push, pull_request]

jobs:
  lint:
    name: Static analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.7.9"
          - "3.8.5"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install Python dependencies
        run: |
          pip install '.[test]'

      - name: Check by flake8
        run: |
          flake8 python tests

      - name: Check by isort
        run: |
          isort **/*.py --check-only

      - name: Check by black
        run: |
          black --check python tests

  test:
    name: Unit testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.7.9"
          - "3.8.5"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install Python dependencies
        run: |
          pip install '.[test]'

      - name: Run unit testing by pytest
        run: |
          python -m pytest tests
